/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthIndisponivelRouteImport } from './routes/auth-indisponivel'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedDadosRouteImport } from './routes/_authenticated/dados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthConfirmarRouteImport } from './routes/auth/confirmar'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiAccountExportRouteImport } from './routes/api/account/export'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndisponivelRoute = AuthIndisponivelRouteImport.update({
  id: '/auth-indisponivel',
  path: '/auth-indisponivel',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDadosRoute = AuthenticatedDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmarRoute = AuthConfirmarRouteImport.update({
  id: '/auth/confirmar',
  path: '/auth/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth-indisponivel': typeof AuthIndisponivelRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/dados': typeof AuthenticatedDadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
}
export interface FileRoutesByTo {
  '/auth-indisponivel': typeof AuthIndisponivelRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/dados': typeof AuthenticatedDadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth-indisponivel': typeof AuthIndisponivelRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/dados': typeof AuthenticatedDadosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-indisponivel'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/configuracoes'
    | '/criar'
    | '/dados'
    | '/dashboard'
    | '/importar'
    | '/insights'
    | '/projetos'
    | '/relatorios'
    | '/auth/callback'
    | '/auth/confirmar'
    | '/api/account/delete'
    | '/api/account/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-indisponivel'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/configuracoes'
    | '/criar'
    | '/dados'
    | '/dashboard'
    | '/importar'
    | '/insights'
    | '/projetos'
    | '/relatorios'
    | '/auth/callback'
    | '/auth/confirmar'
    | '/'
    | '/api/account/delete'
    | '/api/account/export'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth-indisponivel'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/_authenticated/configuracoes'
    | '/_authenticated/criar'
    | '/_authenticated/dados'
    | '/_authenticated/dashboard'
    | '/_authenticated/importar'
    | '/_authenticated/insights'
    | '/_authenticated/projetos'
    | '/_authenticated/relatorios'
    | '/auth/callback'
    | '/auth/confirmar'
    | '/_authenticated/'
    | '/api/account/delete'
    | '/api/account/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthIndisponivelRoute: typeof AuthIndisponivelRoute
  CadastroRoute: typeof CadastroRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmarRoute: typeof AuthConfirmarRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountExportRoute: typeof ApiAccountExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-indisponivel': {
      id: '/auth-indisponivel'
      path: '/auth-indisponivel'
      fullPath: '/auth-indisponivel'
      preLoaderRoute: typeof AuthIndisponivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dados': {
      id: '/_authenticated/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof AuthenticatedDadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirmar': {
      id: '/auth/confirmar'
      path: '/auth/confirmar'
      fullPath: '/auth/confirmar'
      preLoaderRoute: typeof AuthConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/export': {
      id: '/api/account/export'
      path: '/api/account/export'
      fullPath: '/api/account/export'
      preLoaderRoute: typeof ApiAccountExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedDadosRoute: typeof AuthenticatedDadosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedDadosRoute: AuthenticatedDadosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthIndisponivelRoute: AuthIndisponivelRoute,
  CadastroRoute: CadastroRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmarRoute: AuthConfirmarRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountExportRoute: ApiAccountExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
